# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheval', '0005_auto_20160511_1034'),
        ('profil', '0006_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauMontoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('1', 'lundi'), ('2', 'mardi'), ('3', 'mercredi'), ('4', 'jeudi'), ('5', 'vendredi')], max_length=1)),
                ('heure_debut', models.TimeField()),
                ('duree', models.FloatField()),
                ('classe', models.CharField(max_length=65)),
                ('effectif', models.CharField(max_length=65)),
                ('remarque', models.TextField(blank=True)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='PiquetMontoirEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval')),
                ('montoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monte.CreneauMontoir')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='PiquetMontoirStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval')),
                ('montoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monte.CreneauMontoir')),
            ],
        ),
    ]
