# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_auto_20160511_1224'),
        ('monte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneaumontoir',
            name='classe',
        ),
        migrations.AddField(
            model_name='creneaumontoir',
            name='public',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.Public'),
            preserve_default=False,
        ),
    ]
