# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0022_auto_20160511_1410'),
        ('monte', '0002_auto_20160511_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piquetmontoirstaff',
            name='cheval',
        ),
        migrations.AddField(
            model_name='piquetmontoirstaff',
            name='cheval',
            field=models.ManyToManyField(to='cheval.Cheval'),
        ),
    ]
