# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0030_merge'),
        ('monte', '0004_piquetmontoirstaff_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piquetmontoirstaff',
            name='cheval',
        ),
        migrations.AddField(
            model_name='piquetmontoirstaff',
            name='cheval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval'),
        ),
    ]
