# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0005_auto_20160531_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piquetmontoirstaff',
            name='cheval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval'),
        ),
    ]
