# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0006_auto_20160531_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piquetmontoirstaff',
            name='montoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piquet_staff', to='monte.CreneauMontoir'),
        ),
    ]
