# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0007_auto_20160531_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='piquetmontoirenseignant',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piquetmontoirenseignant',
            name='montoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piquet_enseignant', to='monte.CreneauMontoir'),
        ),
    ]
