# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0013_creneaumontoirenseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneaumontoirenseignant',
            name='encadrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='profil.Profil'),
        ),
    ]
