# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0016_auto_20160609_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneaumontoir',
            name='encadrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.Profil'),
        ),
    ]
