# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monte', '0019_auto_20160610_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piquetmontoirenseignant',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.Profil'),
        ),
    ]
