# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cavalier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sire', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=100)),
                ('pedigree', models.CharField(max_length=500)),
                ('annee_naissance', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
                ('embouchure', models.CharField(max_length=60)),
                ('enrennement', models.CharField(max_length=60)),
                ('ferrage', models.DateField()),
                ('remarques', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline_Cheval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Cheval')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Ecurie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('aptitude', models.ForeignKey(default='Apte', on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Aptitude')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Cheval')),
            ],
        ),
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Monte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duree', models.FloatField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Discipline')),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Encadrant')),
            ],
        ),
        migrations.CreateModel(
            name='Piquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Cheval')),
                ('monte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Monte')),
            ],
        ),
        migrations.CreateModel(
            name='Piquet_Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavalier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Cavalier')),
                ('piquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Piquet')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registe_Elevage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pathologie', models.CharField(max_length=500)),
                ('acte', models.CharField(max_length=500)),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Cheval')),
            ],
        ),
        migrations.CreateModel(
            name='Soigneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.IntegerField()),
                ('civilite', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='registe_elevage',
            name='soigneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Soigneur'),
        ),
        migrations.AddField(
            model_name='registe_elevage',
            name='veterinaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Veterinaire'),
        ),
        migrations.AddField(
            model_name='monte',
            name='public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Public'),
        ),
        migrations.AddField(
            model_name='encadrant',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Profil'),
        ),
        migrations.AddField(
            model_name='cavalier',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eplefpa.Profil'),
        ),
    ]
