# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheval', '0005_auto_20160511_1034'),
        ('profil', '0006_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreSoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pathologie', models.CharField(max_length=60)),
                ('acte', models.CharField(choices=[(1, 'Soin'), (2, 'Vaccin'), (3, 'Vermifugation'), (4, 'Ferrage'), (4, 'Divers')], max_length=500)),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval')),
                ('soigneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.Profil')),
            ],
        ),
    ]
