# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registresoins',
            name='acte',
            field=models.CharField(choices=[('1', 'Soin'), ('2', 'Vaccin'), ('3', 'Vermifugation'), ('4', 'Ferrage'), ('5', 'Divers')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registresoins',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
