# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_auto_20160517_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registresoins',
            name='date',
            field=models.DateField(),
        ),
    ]
