# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_auto_20160519_0925'),
        ('sante', '0002_auto_20160517_1639'),
    ]

    operations = [
    ]
