# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registresoins',
            name='date',
            field=models.DateField(),
        ),
    ]
