# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0007_auto_20160531_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistreSoins',
            new_name='Soin',
        ),
        migrations.AlterModelOptions(
            name='soin',
            options={},
        ),
    ]
