# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude', models.CharField(default='apte', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sire', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=100)),
                ('pedigree', models.CharField(max_length=500)),
                ('annee_naissance', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('activite', models.CharField(choices=[(1, 'Monte'), (2, 'Elevage')], max_length=500)),
                ('remarques', models.CharField(max_length=60)),
                ('aptitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Aptitude')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[(1, 'Emplacement 1'), (2, 'Emplacement 2'), (3, 'Emplacement 3'), (4, 'Emplacement 4'), (5, 'Emplacement 5')], max_length=500)),
                ('remarque', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Propri\xe9t\xe9'), (2, 'Commodat'), (3, 'Pension'), (4, 'D\xe9bourrage'), (5, 'Divers')], max_length=500)),
                ('divers', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cheval',
            name='emplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Emplacement'),
        ),
        migrations.AddField(
            model_name='cheval',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Status'),
        ),
    ]
