# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='activite',
            field=models.CharField(choices=[('Monte', 'Monte'), ('Elevage', 'Elevage')], max_length=500),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
    ]
