# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0003_auto_20160510_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='activite',
            field=models.CharField(choices=[('1', 'Monte'), ('2', 'Elevage')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='aptitude',
            field=models.CharField(choices=[('1', 'Apte'), ('2', 'Repos'), ('3', 'Infirmerie'), ('4', 'Autres')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='emplacement',
            field=models.CharField(choices=[('1', 'Emplacement 1'), ('2', 'Emplacement 2'), ('3', 'Emplacement 3'), ('4', 'Emplacement 4'), ('5', 'Emplacement 5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='status',
            field=models.CharField(choices=[('1', 'Propri\xe9t\xe9'), ('2', 'Commodat'), ('3', 'Pension'), ('4', 'D\xe9bourrage'), ('5', 'Divers')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Aptitude',
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
