# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0004_auto_20160510_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cheval',
            name='aptitude',
            field=models.CharField(choices=[('1', 'Apte'), ('2', 'Repos'), ('3', 'Infirmerie'), ('4', 'Autres')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='remarques',
            field=models.TextField(),
        ),
    ]
