# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0004_auto_20160510_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='annee_naissance',
            field=models.CharField(max_length=60),
        ),
    ]
