# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0005_auto_20160511_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Cheval')),
            ],
        ),
        migrations.RenameField(
            model_name='emplacement',
            old_name='adresse',
            new_name='box',
        ),
        migrations.AddField(
            model_name='adresse',
            name='emplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheval.Emplacement'),
        ),
    ]
