# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0011_auto_20160511_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='emplacement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplacement', to='cheval.Emplacement', verbose_name='emplacement'),
        ),
    ]
