# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0014_auto_20160511_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='date_entree',
            field=models.DateField(default=datetime.date(2016, 5, 11)),
        ),
    ]
