# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0015_auto_20160511_1158'),
        ('cheval', '0005_auto_20160511_1034'),
    ]

    operations = [
    ]
