# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0017_auto_20160511_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='date_entree',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
