# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0020_auto_20160511_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='date_entree',
            field=models.DateField(null=True),
        ),
    ]
