# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0023_auto_20160518_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheval',
            old_name='statut',
            new_name='status',
        ),
    ]
