# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0025_auto_20160519_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
