# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0026_auto_20160520_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='photo',
            field=models.FileField(upload_to='photos'),
        ),
    ]
