# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0029_merge'),
        ('cheval', '0028_auto_20160526_0917'),
    ]

    operations = [
    ]
