# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0031_auto_20160531_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheval',
            name='annee_naissance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cheval',
            name='pedigree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='box',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='zone',
            field=models.CharField(max_length=100),
        ),
    ]
