# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0033_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name_plural': 'Journaux'},
        ),
    ]
