# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0034_auto_20160614_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='objet',
            field=models.CharField(choices=[('1', 'Entr\xe9e'), ('2', 'Sortie')], default='1', max_length=1),
        ),
    ]
