# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheval', '0035_journal_objet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='objet',
        ),
    ]
