# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('license', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=3)),
                ('adresse', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('siret', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='periode',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.Profil'),
        ),
    ]
