# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20160510_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='categorie',
            field=models.CharField(choices=[('1', 'El\xe8ve'), ('2', 'Cavalier'), ('3', 'Professeur'), ('4', 'Personnel')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
