# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_profil_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='categorie',
            field=models.CharField(choices=[('1', 'El\xe8ve'), ('2', 'Cavalier'), ('3', 'Professeur'), ('4', 'Personnel'), ('5', 'Autre')], max_length=1),
        ),
    ]
