# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20160510_0941'),
        ('profil', '0005_auto_20160510_1225'),
        ('profil', '0003_auto_20160510_0949'),
    ]

    operations = [
    ]
