# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20160511_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='periode',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='prenom',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='tel_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='tel_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='tel_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periode',
            name='public',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.Public'),
            preserve_default=False,
        ),
    ]
