# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_auto_20160511_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='siret',
        ),
    ]
