# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_remove_profil_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='civilite',
            field=models.CharField(choices=[('1', 'Mr'), ('2', 'Mme'), ('3', 'Mlle')], max_length=3),
        ),
    ]
