# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_remove_profil_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='fin',
            field=models.DateField(null=True),
        ),
    ]
