# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='categorie',
            field=models.CharField(choices=[('1', 'El\xe8ve'), ('2', 'Cavalier'), ('3', 'Professeur'), ('4', 'Personnel'), ('5', 'Autre')], default=datetime.datetime(2016, 5, 26, 9, 35, 3, 75743, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
