# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0018_periode_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='periode',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='public',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.Public'),
        ),
    ]
