# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0020_auto_20160526_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
