# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0021_profil_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='is_active',
            new_name='profil_actif',
        ),
    ]
