# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0022_auto_20160526_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='mdp',
            field=models.CharField(default='plop48000', max_length=20),
        ),
    ]
