# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0023_profil_mdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='mdp',
        ),
    ]
