# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0024_remove_profil_mdp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'permissions': (('say_youpi', 'Can say youpi'),)},
        ),
    ]
