# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0025_auto_20160608_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'permissions': (('look_profil', 'Can look profil'),)},
        ),
    ]
