# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0026_auto_20160608_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'permissions': (('chef_ecurie', 'Look all and modif Chevaux and Monte'), ('professeur', 'Look all and modif Piquet cours'))},
        ),
    ]
