# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0030_auto_20160608_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='permis',
            field=models.CharField(blank=True, choices=[('chef_ecurie', "Chef d'\xe9curie"), ('professeur', 'Professeur')], max_length=30, null=True),
        ),
    ]
