# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0034_auto_20160609_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='permis',
            field=models.CharField(choices=[('1', "Chef d'\xe9curie"), ('2', 'Professeur')], max_length=30),
            preserve_default=False,
        ),
    ]
