# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0035_auto_20160609_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='permis',
            field=models.CharField(choices=[('1', "Chef d'\xe9curie"), ('2', 'Professeur')], default='Professeur', max_length=30),
        ),
    ]
