# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0036_auto_20160609_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='permis',
            field=models.CharField(choices=[('2', 'Professeur'), ('1', "Chef d'\xe9curie")], default='Professeur', max_length=30),
        ),
    ]
