# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0037_auto_20160609_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='permis',
            field=models.CharField(choices=[('1', 'Professeur'), ('2', "Chef d'\xe9curie")], default='Professeur', max_length=30),
        ),
    ]
